# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_IQJyBR5-edj5HkZDDP-HaVQTHHbMnt
"""

!pip install kaggle

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d kanchana1990/japanese-airlines-reviews

import zipfile
with zipfile.ZipFile('japanese-airlines-reviews.zip', 'r') as zip_ref:
    zip_ref.extractall('japanese-airlines-reviews')

import pandas as pd
df = pd.read_csv('japanese-airlines-reviews/JAL_tripadvisor_reviews.csv')
df.head()

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['travel_date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='helpful_votes', y='travel_date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['published_date'].value_counts()
    for x_label, grp in _df_14.groupby('text')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('text')
_ = plt.ylabel('published_date')

!kaggle datasets download -d kanchana1990/japanese-airlines-reviews

df = pd.read_csv('japanese-airlines-reviews/JAL_tripadvisor_reviews.csv')
df.head(3)

df['rating'].mean()

vc=df['lang'].value_counts()

vc.index

vc.values

plt.style.available

plt.figure(figsize=(16,6))
plt.style.use("fivethirtyeight")
plt.bar(vc.index,vc.values,color=["#f96622","#010101"])
plt.show()

vc

vc6=vc[0:6]

diger=vc[6:].sum()

vc6=dict(vc6)

vc6['diger']=diger

vc6

renkler=["#f96622"]*(len(vc6)-1)+["#010101"]

plt.style.use("fivethirtyeight")
plt.figure(figsize=(16,6))
plt.bar(vc6.keys(),vc6.values(),color=renkler)
plt.title("The number of reviews categorized by language.")
plt.xlabel("Language")
plt.ylabel("Total count of reviews")
plt.show()

print(df['rating'].head())
print(df['rating'].unique())

sns.countplot(x=df['rating'])
plt.title("Rating Distribution")
plt.show()

df['title_length'] = df['title'].apply(len)
df['text_length'] = df['text'].apply(len)
sns.histplot(df['text_length'], bins=20, kde=True)
plt.title("Text Length Distribution")
plt.show()

sns.histplot(df['helpful_votes'], bins=20, kde=True)
plt.title("Helpful Votes Distribution")
plt.show()

numeric_df = df.select_dtypes(include=[np.number])

plt.figure(figsize=(8, 6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

print(df.columns)

df.columns = df.columns.str.lower()
print(df.columns)

print(df.head())

sns.boxplot(x='rating', y='helpful_votes', data=df, palette='coolwarm')
plt.title("Helpful Votes by Rating")
plt.xlabel("Rating")
plt.ylabel("Helpful Votes")
plt.show()

df['published_date'] = pd.to_datetime(df['published_date'])
df['year'] = df['published_date'].dt.year

sns.countplot(x='year', data=df, palette='Set2')
plt.title("Number of Reviews by Year")
plt.xlabel("Year")
plt.ylabel("Count")
plt.show()